# MySQL Configuration
spring.datasource.url=jdbc:mysql://root:wabyZSQOdsWUrVBwVafNvLEzGXKlObwQ@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=wabyZSQOdsWUrVBwVafNvLEzGXKlObwQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=3306

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juannomesque12@gmail.com
spring.mail.password=mlao jiuh sayc keif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
